kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # ingress port for nginx
  - containerPort: 30080
    hostPort: 80
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 30443
    hostPort: 443
    listenAddress: "0.0.0.0"
    protocol: TCP
  # API service extension for cluster communication (v1.cluster.loft.sh)
  - containerPort: 8443
    hostPort: 8443
    listenAddress: "0.0.0.0"
    protocol: TCP
  # Webhook validation and enforcement (loft webhook)
  - containerPort: 9443
    hostPort: 9443
    listenAddress: "0.0.0.0"
    protocol: TCP
  # Management API for platform administration (v1.management.loft.sh)
  - containerPort: 9444
    hostPort: 9444
    listenAddress: "0.0.0.0"
    protocol: TCP
  # Prometheus metrics proxy for cost monitoring
  - containerPort: 9090
    hostPort: 9090
    listenAddress: "0.0.0.0"
    protocol: TCP
- role: worker
- role: worker
networking:
  disableDefaultCNI: false