---
apiVersion: v1
kind: Service
metadata:
  name: nginx-vc1
  namespace: vc1
spec:
  selector:
    app: nginx-vc1
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vc1
  namespace: vc1
spec:
  selector:
    matchLabels:
      app: nginx-vc1
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-vc1
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
          - name: http
            containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-vc1-ingress
  namespace: vc1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /vc1
        pathType: Prefix
        backend:
          service:
            name: nginx-vc1
            port:
              number: 80